version: '2'
services:
  redis:
    image: redis:6.0.9
    ports:
      - "6379:6379"
  redis_test:
    image: redis:6.0.9
    ports:
      - "16379:6379"
  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=verysecret
